language: node_js
sudo: true
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm install
install:
|
  npm install -g npm@latest
  npm --version
  npm install --registry https://registry.npmjs.org

script:
  - npm run test
  # - npm run dev
  # - npm run build
  # - npm run checkdir
after_script:
  - npm run coverage
  # Send coverage data to Coveralls after _script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
